name: Update channels.json and videos.json from Youtube Data API

on:
  schedule:
    - cron: '0 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: |
          echo "hello Github Actions"
          echo "::add-mask::Mona The Octocat"
